### ISSUE TITLE
更新失败

### ISSUE THREAD

**Issue by iniwex5** [startpenghubingzhou/AnywhereEFI#1]
第一次更新提示更新失败,第二次更新卡在replace /tmp/efithistemp/Docs/Changelog.md? [y]es, [n]o, [A]ll, [N]one, [r]ename:

**Comment by startpenghubingzhou** [comment]
这个应该跟我没有设置清理文件有关  我会在新提交里面  加入这个功能  到时候注意编译测试

**Comment by startpenghubingzhou** [comment]
/Users/phbz/Library/Developer/Xcode/DerivedData/AnywhereEFI-awonogwvorgddegdneapphrlrsti/Build/Products/Debug/AnywhereEFI
用这个测试下  看看还有没有这个问题

**Comment by iniwex5** [comment]
重新编译后测速 还是那样  卡在那个位置

**Comment by startpenghubingzhou** [comment]
> 重新编译后测速 还是那样 卡在那个位置

你现在用下我提交的预发布版本0.0.1试一次

**Comment by iniwex5** [comment]
还是一样的结果

**Comment by startpenghubingzhou** [comment]
> 还是一样的结果

已经把这个加入到bug里面  我在明天解决下  你贴张图放到这里

**Comment by startpenghubingzhou** [comment]
重新试一下目前的新提交  https://github.com/startpenghubingzhou/AnywhereEFI/commit/405c46a04f6ca9d65fd9677e63cb5a0804243366： 
[AnywhereEFI.zip](https://github.com/startpenghubingzhou/AnywhereEFI/files/3921246/AnywhereEFI.zip)

**Comment by startpenghubingzhou** [comment]
> 第一次更新提示更新失败,第二次更新卡在replace /tmp/efithistemp/Docs/Changelog.md? [y]es, [n]o, [A]ll, [N]one, [r]ename:

你现在试试最新的release

**Comment by startpenghubingzhou** [comment]
目前无法确定这个问题是否依旧存在，但在目前接受的反馈里，尚未发现这个问题。目前我将要暂时关闭这个issue，直到您再次发现这个问题并重启它。
