### ISSUE TITLE
[建议]挂载EFI分区时显示设备名称/宗卷名称

### ISSUE THREAD

**Issue by heyxiaobai** [startpenghubingzhou/AnywhereEFI#2]

**Comment by startpenghubingzhou** [comment]
已经把这个标记为新特性  并在未来的版本中加入  请详细描述下这个新特性

**Comment by heyxiaobai** [comment]
在有多个硬盘时，每个硬盘都有一个EFI分区，使用AnywhereEFI挂载，只能显示number和location，这会导致分不清需要挂载哪个硬盘的EFI分区，而加上设备名称，如“HP SSD xxx"、"WDC PC xxx"，这样可以清楚的选择分区。而如果一个硬盘有多个EFI分区，宗卷名称可以清楚的选择挂载哪个分区【因为我没有多个分区，后者只是一个推测】。（参考Hackintool -- 硬盘）

**Comment by heyxiaobai** [comment]
【建议】 在增加一个挂载情况，比如一个EFI分区已经挂载了，可以显示出来。

**Comment by startpenghubingzhou** [comment]
> 【建议】 在增加一个挂载情况，比如一个EFI分区已经挂载了，可以显示出来。

这是一个不错的建议。不过实行起来 可能会略有难度。主要的难点在于这个信息的提取以及保存

**Comment by crazyhulk** [comment]
@startpenghubingzhou 
你好， 我已经针对该 issues 提出了解决方案， 貌似我没有权限推代码，也不能发起 pull requests.

Hello, I have solved this issues, but I have no access rights to make a pull requests.
![image](https://user-images.githubusercontent.com/13976375/72214972-b131c300-3547-11ea-9729-3dcdd51871c2.png)

**Comment by startpenghubingzhou** [comment]
> @startpenghubingzhou
> 你好， 我已经针对该 issues 提出了解决方案， 貌似我没有权限推代码，也不能发起 pull requests.
> 
> Hello, I have solved this issues, but I have no access rights to make a pull requests.
> ![image](https://user-images.githubusercontent.com/13976375/72214972-b131c300-3547-11ea-9729-3dcdd51871c2.png)

我检查过了，我没有关闭pr权限，你重新推一下试试看，我需要些时间检查一下

**Comment by CrazyHulk** [comment]
> > @startpenghubingzhou
> > 你好， 我已经针对该 issues 提出了解决方案， 貌似我没有权限推代码，也不能发起 pull requests.
> > Hello, I have solved this issues, but I have no access rights to make a pull requests.
> > ![image](https://user-images.githubusercontent.com/13976375/72214972-b131c300-3547-11ea-9729-3dcdd51871c2.png)
> 
> 我检查过了，我没有关闭pr权限，你重新推一下试试看，我需要些时间检查一下

我现在是分支推不上去，不是 Contributors ？

**Comment by crazyhulk** [comment]
> > @startpenghubingzhou
> > 你好， 我已经针对该 issues 提出了解决方案， 貌似我没有权限推代码，也不能发起 pull requests.
> > Hello, I have solved this issues, but I have no access rights to make a pull requests.
> > ![image](https://user-images.githubusercontent.com/13976375/72214972-b131c300-3547-11ea-9729-3dcdd51871c2.png)
> 
> 我检查过了，我没有关闭pr权限，你重新推一下试试看，我需要些时间检查一下

好，有时间你看一下

**Comment by startpenghubingzhou** [comment]
目前合并的PR #6 应该已经解决了你所说的问题，并且在我的机子上没有问题。感谢@CrazyHulk的提交。目前我将要关闭这个issue，如果后续还有这个问题，请联系我，并再次开启这个issue，谢谢！

**Comment by heyxiaobai** [comment]
感谢两位大佬 @CrazyHulk @startpenghubingzhou
