### ISSUE TITLE
[建议]选项顺序调整

### ISSUE THREAD

**Issue by heyxiaobai** [startpenghubingzhou/AnywhereEFI#3]
建议先选择功能（“选择挂载EFI、备份EFI、升级EFI”），在选择升级EFI的时候，再进行选择是Clover还是OC引导。（因为挂载EFI、备份EFI与是什么引导无关）

**Comment by startpenghubingzhou** [comment]
感谢建议，会在后续进行调整

**Comment by startpenghubingzhou** [comment]
https://github.com/startpenghubingzhou/AnywhereEFI/commit/405c46a04f6ca9d65fd9677e63cb5a0804243366 我已经在这个提交中更改了顺序  现在我将关闭这个问题 如果这个提交不符合你的描述  请再次打开这个问题
