### ISSUE TITLE
[建议]简短名字，移入usr/local/bin

### ISSUE THREAD

**Issue by findyy99** [startpenghubingzhou/AnywhereEFI#4]
由于在命令行下操作，可以把名字改短，且在readme.md添加将其移入us r/local/bin，目录，这样就不用到处找了

**Comment by startpenghubingzhou** [comment]
这些你自己手动完成即可

**Comment by sarkrui** [comment]
一条命令安装 AnywhereEFI
```bash
wget --no-check-certificate https://github.com/startpenghubingzhou/AnywhereEFI/releases/download/0.1/AnywhereEFI-0.1.zip && tar -xvf AnywhereEFI*.zip && cp AnywhereEFI /usr/local/bin
```

**Comment by startpenghubingzhou** [comment]
> 一条命令安装 AnywhereEFI
> 
> ```shell
> wget --no-check-certificate https://github.com/startpenghubingzhou/AnywhereEFI/releases/download/0.1/AnywhereEFI-0.1.zip && tar -xvf AnywhereEFI*.zip && cp AnywhereEFI /usr/local/bin
> ```

考虑到国内用户下载GitHub的速度并不是很快，且此文件存在复用可能，我不推荐这么做。
